server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://dpg-d553t6mr433s73dceui0-a:5432/postgresql_hw3h
    username: fecredit_db_user
    password: nJS8CJpOW410BOyAQ6EHv3YCZF4qqQWj

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

